name = "Widdlemon"
author = "Widdlemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4be5f247517f483f4b52f4c026d33a0192490ccf868fc0a5e6112f0279a94fad"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
