name = "Widdlemon"
author = "Widdlemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "145c56b6b7afaae32663c53b85843e88b0e9a669b4a840ac33013888d412f27a"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
