name = "Widdlemon"
author = "Widdlemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95c990f637b48d94bb61183f864faf1253fae23c29333340ad5fb08b56a0796c"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
