#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 23:50:18 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
